version: 2.1
orbs:
   aws-cli: circleci/aws-cli@1.0
   serverless: circleci/serverless-framework@1.0.1
jobs:
   one:
     executor: serverless/default
     docker:
       # specify the version you desire here
       - image: circleci/python:3.6.1
     steps:
       - checkout
       - aws-cli/setup
       - serverless/setup
       - run:
             name: Install Serverless CLI and dependencies
             command: |
               serverless plugin install -n serverless-python-requirements
       - run: sls deploy

workflows:
  one_and_two:
    jobs:
      - one