version: 2.1
orbs:
   aws-cli: circleci/aws-cli@2.0
   serverless: circleci/serverless-framework@2.0
jobs:
   one:
     executor: serverless/default
     steps:
       - checkout
       - aws-cli/setup
       - serverless/setup
       - run:
             name: Install Serverless CLI and dependencies
             command: |
               serverless plugin install -n serverless-python-requirements
       - run: sls deploy

workflows:
  one_and_two:
    jobs:
      - one